manifest_version = 2
name = "Portuguese Language"
version = "1.0.0"
author = "Ed1z_19"
description = "Tradução para o Menu Arcade do Xbox 360, não afeta o jogo em geral."
code = "pt_language"
game_version = "1.4.2"
